config/routes.rb
Rails.application.routes.draw do
  get '/actualites',  to: 'pages#actualites'
  devise_for :users
  devise_scope :user do
   get '/users/sign_out', to: 'devise/sessions#destroy'
end
  root to: 'pages#home'


  get'/dashboard', to: 'pages#dashboard'
  scope '/dashboard' do
    get '/cerfa_informations', to: 'pages#cerfa_informations'




    get '/invoices/:id/calculate/', to: 'invoices#calculate', as: :invoices_calculate
    post '/invoices/calculate', to: 'invoices#calculate'

    get '/my_informations', to: 'users#informations'
    get '/company_registration',  to: 'users#company_registration'
    get '/services',  to: 'pages#services'
    get '/demarches',  to: 'users#demarches'
    get '/relances/:id', to: 'relances#show', :defaults => { :format => 'docx' }
    get '/relance/new', to: 'relances#new'

    get '/miseendemeure/:id', to: 'miseendemeures#show', :defaults => { :format => 'docx' }, as: :miseendemeure_show

    get '/comptabilites/:id', to: 'comptabilites#show_calculate', :defaults => { :format => 'docx' }, as: :show_calculate

    get '/comptabilite/new', to: 'comptabilites#new', as: :new_comptabilite


    get '/comptabilites/:id/calculate/', to: 'comptabilites#calculate', as: :comptabilites_calculate
    post '/comptabilites/:id/calculate', to: 'comptabilites#calculate'

    get '/relances', to: 'relances#lettre', :defaults => { :format => 'docx' }


  get '/devis/:id/show/', to: 'devis#show', as: :devi_show

  get '/devis/search', to: 'devis#search', as: :devi_search

  get '/devis/resultat', to: 'devis#resultat', as: :resultat_devi
  get '/devis/:id/sucess/', to: 'devis#success', as: :devi_success



    # get '/personal_info', to: 'users#personal_info_users'
    # get '/company_info', to: 'users#company_info_users'
    resources :invoices
    resources :taxes, only: [:index]


    resources :comptabilites

    resources :devis
    resources :relances
    resources :miseendemeures, only: [:new, :create]
    resources :achats
    resources :clients
    resources :controledegestions

  end

  resources :users, only: [:update] # Pas propre car current_user donc pas besoin d'id mais choisi par Joseph pour faciliter les simple forms
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/comptabilite.rb
class Comptabilite < ApplicationRecord
  belongs_to :user
  validates :user, uniqueness: true
  has_and_belongs_to_many :invoices

end

app/controllers/comptabilites_controller.rb
class ComptabilitesController < ApplicationController


  skip_before_action :verify_authenticity_token




  def new
    @comptabilite= Comptabilite.new

  end

  def show
    @comptabilite=Comptabilite.find(params[:id])
    @comptabilites = Comptabilite.all

  end

  def create
    @comptabilite = Comptabilite.new(comptabilite_params)
    @comptabilite.user = current_user
    if @comptabilite.save
        redirect_to root_path, notice: "Vos données ont bien été enregistrées"
    else
        render "new"
    end
  end

  def edit
     @comptabilite = Comptabilite.find(params[:id])
  end

  def update
    @comptabilite = Comptabilite.find(params[:id])
    @comptabilite.update!(comptabilite_params)
    redirect_to root_path

  end



  def calculate

    @invoices = Invoice.find_by(user:current_user)


  if @comptabilite.nil?
    @comptabilite = 0
    redirect_to new_comptabilite_path

  else
   @charges_variables = @comptabilite.charges_repartir
    @charges_fixes = 6000


    @bfr = (@comptabilite.stocks+@comptabilite.creance)-(@comptabilite.dettes_exploitations+@comptabilite.dettes_fiscales)
    @caf = (@comptabilite.resultats+@comptabilite.charges_repartir) - (@comptabilite.achats_marchandises)
    @marge = (@comptabilite.ventes_marchandises-@comptabilite.achats_marchandises)
    @taux_marge = @marge/@comptabilite.ventes_marchandises
    @seuil_rentabilite = @comptabilite.chiffre_affaire/@charges_fixes
    @taux_rentabilité = @comptabilite.ventes_marchandises/@comptabilite.achats_marchandises
    @chiffre_a_rentrer = @comptabilite.ventes_marchandises - @comptabilite.achats_marchandises
    @reste_a_payer = @comptabilite.stocks + @comptabilite.valeur_credit_bail
    @ebe = "25 000"
    @marge_cout_variable = @comptabilite.chiffre_affaire - @comptabilite.charges_repartir
    @independance_financière = @comptabilite.capitaux_propres/@comptabilite.dettes_financieres
    @marge_sécurite = "2000"
  end

  end

  def show_calculate
    @comptabilite = Comptabilite.find_by(params[:user_id])

    @charges_variables = @comptabilite.charges_repartir/3
    @charges_fixes = @comptabilite.charges_repartir- @charges_variables


    @bfr = (@comptabilite.stocks+@comptabilite.creance)-(@comptabilite.dettes_exploitations+@comptabilite.dettes_fiscales)
    @caf = (@comptabilite.resultats+@comptabilite.charges_repartir) - (@comptabilite.achats_marchandises)
    @marge = (@comptabilite.ventes_marchandises-@comptabilite.achats_marchandises)
    @taux_marge = @marge/@comptabilite.ventes_marchandises
    @seuil_rentabilite = @comptabilite.chiffre_affaire/@charges_fixes
    @taux_rentabilité = @comptabilite.ventes_marchandises/@comptabilite.achats_marchandises
    @chiffre_a_rentrer = @comptabilite.ventes_marchandises - @comptabilite.achats_marchandises
    @reste_a_payer = @comptabilite.stocks + @comptabilite.valeur_credit_bail
    @ebe = "25 000"
    @marge_cout_variable = @comptabilite.chiffre_affaire - @comptabilite.charges_repartir
    @independance_financière = @comptabilite.capitaux_propres/@comptabilite.dettes_financieres
    @marge_sécurite = "2000"
    respond_to do |format|
    format.docx do
      render docx: 'presentation_financiere.docx.erb', filename: 'presentation_financiere.docx'

   end
   end
  end

  def destroy
    @comptabilite = Comptabilite.find(params[:id])
    @comptabilite.destroy
    redirect_to root
  end

  def update
     @comptabilite = Comptabilite.find(params[:id])
    @comptabilite.update!(comptabilite_params)
    redirect_to root_path
  end

  private




  def set_user
    @user = current_user

  end

  def comptabilite_params
      params.require(:comptabilite).permit(:immobilisations, :valeur_credit_bail, :charges_repartir, :primes_remboursement, :stocks, :avances, :creance, :effets_escomptes, :valeur_mobilieres,
       :disponibilites, :capitaux_propres, :dettes_financieres, :emprunt_credit_bail,
       :dettes_exploitations, :dettes_fiscales, :tresorerie_passive, :resultats, :achats_marchandises, :chiffre_affaire)
end


end

app/views/comptabilites/_compta_form.html.erb
<%= simple_form_for(@compta, remote: true) do |f| %>
  <div class="form-title py-3">
    <h2 class="text-warning">Informations préalables</h2>
  </div>
  <table class="table table-sm table-striped">
    <tbody>
      <tr>
        <td class="text-primary form-col"> <%= f.label :immobilisations,label: "Quels sont vos niveaux d'immobilisations?" %></td>
        <td> <%= f.input_field :immobilisations, class: "form-control" %></td>
      </tr>
      <tr>
        <td class=" text-primary"> <%= f.label :valeur_credit_bail, "Valeur du crédit bail" %></td>
        <td> <%= f.input_field :valeur_credit_bail, class: "form-control" %></td>
      </tr>
      <tr>
        <td class=" text-primary"> <%= f.label :charges_repartir, "Avez-vous des charges ?" %></td>
        <td> <%= f.input_field :charges_repartir,  class: "form-control" %></td>
      </tr>
      <tr>
       <td class=" text-primary"> <%= f.label :primes_remboursement, "Avez-vous des primes?" %></td>
        <td> <%= f.input_field :primes_remboursement,  class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <div class="form-title py-3">
    <h2 class="text-warning">Déclaration à l'actif circulant</h2>
  </div>
  <table class="table table-sm table-striped">
    <tbody>
      <tr>
        <td class="text-primary form-col"> <%= f.label :stocks,label: "Déclaration du stock" %></td>
        <td> <%= f.input_field :stocks,  class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary form-col"> <%= f.label :avances,label: "Avances" %></td>
        <td> <%= f.input_field :avances, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :creance, label: "Créances" %></td>
        <td> <%= f.input_field :creance, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :effets_escomptes,label: "Effets escomptés" %></td>
        <td> <%= f.input_field :effets_escomptes, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :valeur_mobiliere,label: "Valeurs mobilières" %></td>
        <td> <%= f.input_field :valeur_mobilieres, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :disponibilites,label: "Disponibilités" %></td>
        <td> <%= f.input_field :disponibilites, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :capitaux_propres,label: "Montant des capitaux propres" %></td>
        <td> <%= f.input_field :capitaux_propres, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_financieres, label: "Dettes_financieres" %></td>
        <td> <%= f.input_field :dettes_financieres, class:"form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :emprunt_credit_bail,label: "Emprunt Crédit Bail" %></td>
        <td> <%= f.input_field :emprunt_credit_bail, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_exploitations,label: "Dettes d'exploitation " %></td>
        <td> <%= f.input_field :dettes_exploitations, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_fiscales, label: "Dettes fiscales" %></td>
        <td> <%= f.input_field :dettes_fiscales, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :tresorerie_passive,label: "Trésorerie passive" %></td>
        <td> <%= f.input_field :tresorerie_passive, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <%= f.submit "Validez vos données", class: "btn btn-warning"%>
<% end %>

app/views/comptabilites/_simple_form.html.erb
<%= simple_form_for(@comptabilite, remote: true) do |f| %>
  <div class="form-title py-3">
    <h2 class="text-warning">Informations préalables</h2>
  </div>
  <table class="table table-sm table-striped">
    <tbody>
      <tr>
        <td class="text-primary form-col"> <%= f.label :name, label: "Quel est le nom de votre entreprise ?" %></td>
        <td> <%= f.input_field :name, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary form-col"> <%= f.label :immobilisations,label: "Quels sont vos niveaux d'immobilisations?" %></td>
        <td> <%= f.input_field :immobilisations, class: "form-control" %></td>
      </tr>
      <tr>
        <td class=" text-primary"> <%= f.label :valeur_credit_bail, "Valeur du crédit bail" %></td>
        <td> <%= f.input_field :valeur_credit_bail, class: "form-control" %></td>
      </tr>
      <tr>
        <td class=" text-primary"> <%= f.label :charges_repartir, "Avez-vous des charges ?" %></td>
        <td> <%= f.input_field :charges_repartir,  class: "form-control" %></td>
      </tr>
      <tr>
       <td class=" text-primary"> <%= f.label :primes_remboursement, "Avez-vous des primes?" %></td>
        <td> <%= f.input_field :primes_remboursement,  class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <div class="form-title py-3">
    <h2 class="text-warning">Déclaration à l'actif circulant</h2>
  </div>
  <table class="table table-sm table-striped">
    <tbody>
      <tr>
        <td class="text-primary form-col"> <%= f.label :stocks,label: "Déclaration du stock" %></td>
        <td> <%= f.input_field :stocks,  class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary form-col"> <%= f.label :avances,label: "Avances" %></td>
        <td> <%= f.input_field :avances, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :creance, label: "Créances" %></td>
        <td> <%= f.input_field :creance, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :effets_escomptes,label: "Effets escomptés" %></td>
        <td> <%= f.input_field :effets_escomptes, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :valeur_mobiliere,label: "Valeurs mobilières" %></td>
        <td> <%= f.input_field :valeur_mobilieres, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :disponibilites,label: "Disponibilités" %></td>
        <td> <%= f.input_field :disponibilites, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :capitaux_propres,label: "Montant des capitaux propres" %></td>
        <td> <%= f.input_field :capitaux_propres, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_financieres, label: "Dettes_financieres" %></td>
        <td> <%= f.input_field :dettes_financieres, class:"form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :emprunt_credit_bail,label: "Emprunt Crédit Bail" %></td>
        <td> <%= f.input_field :emprunt_credit_bail, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_exploitations,label: "Dettes d'exploitation " %></td>
        <td> <%= f.input_field :dettes_exploitations, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :dettes_fiscales, label: "Dettes fiscales" %></td>
        <td> <%= f.input_field :dettes_fiscales, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :tresorerie_passive,label: "Trésorerie passive" %></td>
        <td> <%= f.input_field :tresorerie_passive, class: "form-control" %></td>
      </tr>
       <tr>
        <td class="text-primary"> <%= f.label :resultats,label: "Résultats" %></td>
        <td> <%= f.input_field :resultats, class: "form-control" %></td>
      </tr>
      <tr>
        <td class="text-primary"> <%= f.label :achats_marchandises,label: "Achats de Marchandises" %></td>
        <td> <%= f.input_field :achats_marchandises, class: "form-control" %></td>
      </tr>
       <tr>
        <td class="text-primary"> <%= f.label :chiffre_affaire,label: "Chiffre d'affaires total" %></td>
        <td> <%= f.input_field :chiffre_affaire, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <%= f.submit "Validez vos données", class: "btn btn-warning"%>
<% end %>

app/views/comptabilites/calculate.html.erb
<%= render 'shared/navbar' %>
<%= render '/pages/sidebar' %>

<div class="dashboard-content" style="margin-left: 250px; margin-right: 30px">


    <div class="row pt-4 d-flex justify-content-between my-0 py-0">
      <div class="dashboard-upper-part col-xs-12 col-sm-7">
        <div class="dashboard-upper-part-card" style="width: 15%">
          <div><i class="fas fa-chart-line"></i> CA</div>
          <div id="turnover" style="font-size: 1.6rem">
            <span id="monthly-turnover"><%= @chiffre_affaires%> <i class="fas fa-euro-sign"></i> <span class='date-italics'>(<%= @previous_year_month_variation_rate  %>%) <%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Variation par rapport au même chiffre année n-1"></i><% end %></span></span>
            <span id="yearly-turnover" class="d-none"><%= @comptabilite.chiffre_affaire %> <i class="fas fa-euro-sign"></i> <span class='date-italics'>(<%= @previous_year_past_12_month_variation_rate  %>%) <%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Variation par rapport au même chiffre année n-1"></i><% end %></span></span>
            <span id="exercise-turnover" class="d-none"><%= @comptabilite.chiffre_affaire %> <i class="fas fa-euro-sign"></i> <span class='date-italics'>(<%= @previous_year_same_month_exercise_variation_rate  %>%) <%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Variation par rapport au même chiffre année n-1"></i><% end %></span></span>
          </div>
          <div class="d-flex justify-content-center">
            <div>
              <button class="btn btn-ghost active" id="btn-monthly-turnover" >Mois</button>
            </div>
            <div>
              <button class="btn btn-ghost" id="btn-yearly-turnover" >12 Mois</button>
            </div>
            <div>
              <button class="btn btn-ghost" id="btn-exercise-turnover" >Exercice</button>
            </div>
          </div>
        </div>
        <div class="dashboard-upper-part-card" style="width: 15%">
          <div><i class="fas fa-users"></i> Nouveaux clients</div>
          <div style="font-size: 1.6rem">
            <span id="past-month-new-clients">+ 9</span>
            <span id="past-year-new-clients" class="d-none">+ 126</span>
            <span id="this-exercise-new-clients" class="d-none">+ 23</span>
          </div>
          <div class="d-flex justify-content-center">
            <div>
              <button class="btn btn-ghost active" id="btn-month-new-clients" >Mois</button>
            </div>
            <div>
              <button class="btn btn-ghost" id="btn-year-new-clients"  >12 Mois</button>
            </div>
            <div>
              <button class="btn btn-ghost" id="btn-exercise-new-clients" >Exercice</button>
            </div>
          </div>
        </div>
      </div>
      <div class="dashboard-upper-part-card col-xs-12 col-sm-4 pr-0 mr-0" style="width: 30%">
        <div>Les échéances du mois</div>
        <div>
        <span class="text"> Déclaration de chiffres d'affaires avant le 31/03/2021 </span>
      </div>
      </div>
    </div>

    <div class="row pt-4 d-flex justify-content-between my-0 py-0">
        <div class="col-xs-12 col-sm-7 dashboard-chart-card">
          Chiffre d'affaire sur 12 mois glissants
          <canvas id="myChart2" data-monthly-turnover-previous-year= "<%= @monthly_previous_past_12_months_turnover %>"
           data-monthly-turnover-past-year= "<%= @monthly_past_12_months_turnover %>"height="200" aria-label="Hello ARIA World" >
            <p>Hello Fallback World</p>
          </canvas>
        </div>
        <div class="col-xs-12 col-sm-4 dashboard-chart-card">
          <div class='mb-0'>Chiffre d'affaire de l'année</div>
          <div class= 'date-italics'>(Évolution en % par rapport à l'année précédente)</div>
          <div class='mt-6 py-2'>
            <canvas id="doughnut-chart" data-current-year= "<%= @current_year_data_service %>" data-variation-rate= "<%= @previous_year_same_month_exercise_variation_rate %>" height="200" aria-label="Hello ARIA World" class="pt-6">
              <p>Hello Fallback World</p>
            </canvas>
          </div>
          <div class="py-2 d-flex justify-content-around" style="font-size: 1.2rem">
              <div style="margin-left: 60px">
                <%= @seuil_rentabilite %> <i class="fas fa-euro-sign"></i> / 72000 <i class="fas fa-euro-sign"></i>
              </div>
              <div>
                 <%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="72000€ coorespond au CA max pour votre activité" ></i><% end %>
              </div>
          </div>
          <div class="pb-2 date-italics">
            Estimation de la rentabilité : <%= @seuil_rentabilite %> <i class="fas fa-euro-sign"></i>
          </div>
          <div class="d-flex justify-content-center py-2">
            <div>
              <button class="btn btn-ghost" id="btn-monthly-turnover" style="width: 32px" >2019</button>
            </div>
            <div>
              <button class="btn btn-ghost" id="btn-yearly-turnover" style="width: 32px" >2020</button>
            </div>
            <div>
              <button class="btn btn-ghost active" id="btn-exercise-turnover" style="width: 32px" >2021</button>
            </div>
          </div>
        </div>
    </div>
    <div class="row pt-4 d-flex justify-content-between my-0 py-0">
      <div class="col-12 dashboard-chart-card">

        <div class='mb-2' style="font-size: 1.5rem">VOS chiffres</div>

        <div class='mt-6 py-2'>
          <div class="dashboard-upper-part-card px-0" style="width: 95%">
            <table class="table">
            <tbody>
              <tr>



                <td style="border-top: 0px; font-size: 1.2rem">Vos charges fixes </td>
                <td style="border-top: 0px; opacity: 0.6"><%= @charges_fixes %> <i class="fas fa-euro-sign"></i></td>

                <td class= "date-italics" style="border-top: 0px">31/03/2021</td>
                <td style="border-top: 0px"><span class="badge badge-secondary" style= "background-color: #edae2f">À déclarer</span></td>
                <td style="border-top: 0px"><%= link_to root_path do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="À déclarer à l'URSAFF"></i><% end %></td>
              </tr>
              <tr>


                <td style="font-size: 1.2rem">Vos charges variables</td>
                <td style="opacity: 0.6" >

                    <%= @charges_variables %>


                   <i class="fas fa-euro-sign"></i>
                </td>
                <td class= "date-italics">31/03/2021</td>
                <td><span class="badge badge-secondary" style= "background-color: #0061f2"> À payer </span></td>
                <td><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="À payer à l'URSAFF, calculé sur le CA de février 2021" ></i><% end %></td>
              </tr>
              <tr>


                <td style="font-size: 1.2rem">Charges</td>
                <td style="opacity: 0.6" >
                    <%= @charges_fixes + @charges_variables%>


                  <i class="fas fa-euro-sign"></i>
                </td>
                <td class= "date-italics">31/03/2021</td>
                <td><span class="badge badge-secondary" style= "background-color: #0061f2">À payer</span></td>
                <td><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Calculé sur vos revenus 2019"></i><% end %></td>
              </tr>
                <tr>



                <td style="font-size: 1.2rem">EBE </td>
                <td style="opacity: 0.6"><%= @ebe%> <i class="fas fa-euro-sign"></i></td>

                <td class= "date-italics">02/05/2021 </td>
                <td><span class="badge badge-secondary" style= "background-color: #edae2f">À déclarer</span></td>
                <td><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Calculé sur le CA de 2020"></i><% end %></td>
              </tr>


                <td style="font-size: 1.2rem">Marge de sécurité </td>
                <td style="opacity: 0.6" >

                    <%= @marge_sécurite%>


                   <i class="fas fa-euro-sign"></i>
                </td>
                <td class= "date-italics">30/05/2021</td>
                <td><span class="badge badge-secondary" style= "background-color: #edae2f">À déclarer</span></td>
                <td ><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Montant à déclarer pour l'activité de votre micro-entreprise"></i><% end %></td>
              </tr>
              <tr>



                <td style="font-size: 1.2rem">Perte consolidée</td>

                <td style="opacity: 0.6">823 <i class="fas fa-euro-sign"></i></td>
                <td class= "date-italics">15/09/2021</td>
                <td><span class="badge badge-secondary" style= "background-color: #0061f2">À payer</span></td>
                <td><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="Calculé sur la valeur locative des biens immobiliers de 2019"></i><% end %></td>
              </tr>
              <tr>




                <td style="font-size: 1.2rem">Marge bénéficiaire </td>
                <td style="opacity: 0.6">
                  2500

                   <i class="fas fa-euro-sign"></i>
                </td>
                <td class= "date-italics">30/09/2021</td>
                <td><span class="badge badge-secondary" style= "background-color: #0061f2">À payer</span></td>
                <td><%= link_to '#' do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="" ></i><% end %></td>
              </tr>
            </tbody>
          </table>
             <%= link_to "Format Word", show_calculate_path %>
              <%= link_to "Modifier les informations", edit_comptabilite_path(@comptabilite) %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/comptabilites/edit.html.erb
<%= render 'shared/navbar' %>
<%= render '/pages/sidebar' %>
<div class="dashboard-content">
  <div class="container">
    <h1>Modifier les données de l'entreprise</h1>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <hr>
    <%= render "simple_form", comptabilite: @comptabilite  %>
    <hr>
    <p> La modification de la comptabilité permettra de calculer votre chiffre d'affaires.</p>
    <hr>
    <%= link_to "Back to index", root_path %>
  </div>
</div>

app/views/comptabilites/new.html.erb
<%= render 'shared/navbar_sansachat' %>
<%= render '/pages/sidebar' %>
<div class="dashboard-content">
  <div class="container">
    <div class="dashboard-information">
      <%= render "simple_form", comptabilites: @compta, locals: { user: @user } %>
      <hr>
      <p> L'ajout de factures permettra de calculer votre chiffre d'affaires.</p>
      <hr>
      <%= link_to "Back to index", root_path %>
    </div>
  </div>
</div>

app/views/comptabilites/presentation_financiere.docx.erb
<h2>Analyse financière</h2>

Les chiffres de la société <%= current_user.use_name %> sont les suivants :

Chiffres  :   Données

Chiffre d' affaires : <%= @comptabilite.chiffre_affaire %>

Seuil de rentabilité  :  <%= @seuil_rentabilite %>

Charges variables : <%= @charges_variables %>

Capacité d'auto-financement : <%= @caf %>

app/views/comptabilites/show.html.erb
<%= render 'shared/navbar' %>
<%= render '/pages/sidebar' %>
<div class="dashboard-content">
  <div class="container">

</div>

app/views/comptabilites/update.html.erb
<%= render 'shared/navbar_sansachat' %>
<%= render '/pages/sidebar' %>
<div class="dashboard-content">
  <div class="container">
    <div class="dashboard-information">
      <%= render "simple_form", comptabilites: @compta, locals: { user: @user } %>
      <hr>
      <p> L'ajout de factures permettra de calculer votre chiffre d'affaires.</p>
      <hr>
      <%= link_to "Back to index", root_path %>
    </div>
  </div>
</div>