config/routes.rb
Rails.application.routes.draw do
  get '/actualites',  to: 'pages#actualites'
  devise_for :users
  devise_scope :user do
   get '/users/sign_out', to: 'devise/sessions#destroy'
end
  root to: 'pages#home'


  get'/dashboard', to: 'pages#dashboard'
  scope '/dashboard' do
    get '/cerfa_informations', to: 'pages#cerfa_informations'




    get '/invoices/:id/calculate/', to: 'invoices#calculate', as: :invoices_calculate
    post '/invoices/calculate', to: 'invoices#calculate'

    get '/my_informations', to: 'users#informations'
    get '/company_registration',  to: 'users#company_registration'
    get '/services',  to: 'pages#services'
    get '/demarches',  to: 'users#demarches'
    get '/relances/:id', to: 'relances#show', :defaults => { :format => 'docx' }
    get '/relance/new', to: 'relances#new'

    get '/miseendemeure/:id', to: 'miseendemeures#show', :defaults => { :format => 'docx' }, as: :miseendemeure_show

    get '/comptabilites/:id', to: 'comptabilites#show_calculate', :defaults => { :format => 'docx' }, as: :show_calculate

    get '/comptabilite/new', to: 'comptabilites#new', as: :new_comptabilite


    get '/comptabilites/:id/calculate/', to: 'comptabilites#calculate', as: :comptabilites_calculate
    post '/comptabilites/:id/calculate', to: 'comptabilites#calculate'

    get '/relances', to: 'relances#lettre', :defaults => { :format => 'docx' }


  get '/devis/:id/show/', to: 'devis#show', as: :devi_show

  get '/devis/search', to: 'devis#search', as: :devi_search

  get '/devis/resultat', to: 'devis#resultat', as: :resultat_devi
  get '/devis/:id/sucess/', to: 'devis#success', as: :devi_success



    # get '/personal_info', to: 'users#personal_info_users'
    # get '/company_info', to: 'users#company_info_users'
    resources :invoices
    resources :taxes, only: [:index]


    resources :comptabilites

    resources :devis
    resources :relances
    resources :miseendemeures, only: [:new, :create]
    resources :achats
    resources :clients
    resources :controledegestions

  end

  resources :users, only: [:update] # Pas propre car current_user donc pas besoin d'id mais choisi par Joseph pour faciliter les simple forms
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- JavaScript Bundle with Popper -->
<footer class="bg-light bottom footer">
  <div class="row footer-row justify-content-between">
    <div class="col-3 text-center">
      <div class="footer-brand">
        <%= link_to "Mon Auto-Entreprise", "/",  class: "nav-brand" %>
      </div>
    </div>
    <div class="col-6  text-center">
      <p class=" title text-muted">Mon-Autoentreprise © <%= Time.now.year %> -  Tous droits réservés</p>
    </div>
    <div class="col-3 text-center ">

    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header class="navbar-header">
  <nav class="navbar navbar-expand-lg navbar-expand-md  navbar-light bg-light fixed-top">
    <%= link_to "Mon Auto-Entreprise", "/",  class: "nav-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <%= link_to "Créer son activité", company_registration_path(tab: "personal_info"),  class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer une relance", new_miseendemeure_path(tab: "personal_info"), class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Faire un devis", new_devi_path(tab: "personal_info"), class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "Dashboard", invoices_calculate_path( current_user, @invoice), class: "nav-link dropdown-toggle text-primary", id: "navbarDropdown", role: "button",  :"data-toggle"=> "dropdown", :"aria-haspopup"=> "true",  :"aria-expanded"=> "false" %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Tableau de bord", invoices_calculate_path( current_user, @invoice), class: "dropdown-item text-warning links" %>
              <a class="dropdown-item" href="#">Mes informations</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Mes écheances</a>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Ma liste des achats", achat_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ma liste des Recettes", invoice_path, class: "nav-link text-primary links" %>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link btn btn-sm btn-outline-primary rounded-pill links"%>
        </nav>
      <% else  %>
        <ul class="navbar-nav mx-auto ">
          <li class="nav-item">
            <%= link_to "Créer son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", new_user_registration_path, class: "nav-link text-primary links " %>
          </li>
          <li class="nav-item">
            <li><%= link_to "Dashboard",  new_user_registration_path, class: "nav-link text-primary links" %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Actualités",  actualites_path, class: "nav-link text-primary links" %></li>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <ul class="navbar-nav mx-auto ">
            <%= link_to "Se Connecter", new_user_session_path, class: " nav-link btn btn-sm btn-outline-warning rounded-pill nav-item ", id:"login-btn" %>
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link btn btn-sm  btn-warning rounded-pill  nav-item ml-1", id: "signup-btn" %>
          </ul>
        </nav>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_navbar_animate.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top"  id= "navbar">
    <%= link_to "Mon Auto-Entreprise", "/",  class: "nav-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <%= link_to "Créer son activité", company_registration_path(tab: "personal_info"),  class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer une relance", new_miseendemeure_path(tab: "personal_info"), class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Faire un devis", new_devi_path(tab: "personal_info"), class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">

            <%= link_to "Analyse financière", comptabilites_calculate_path( current_user, @comptabilite), class: "nav-link text-primary links" %>

          </li>
          <li class="nav-item dropdown">
            <%= link_to "Mes services", invoices_calculate_path( current_user, @invoice), class: "nav-link dropdown-toggle text-primary", id: "navbarDropdown", role: "button",  :"data-toggle"=> "dropdown", :"aria-haspopup"=> "true",  :"aria-expanded"=> "false" %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Rentrez des factures", new_invoice_path, class: "dropdown-item text-warning links" %>
              <%= link_to "Tableau de bord", invoices_calculate_path( current_user, @invoice), class: "dropdown-item text-warning links" %>
              <a class="dropdown-item" href="#">Mes informations</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Mes écheances</a>
            </div>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link btn btn-sm  rounded-pill links ",  id: "signup-btn" %>
        </nav>
      <% else  %>
        <ul class="navbar-nav mx-auto ">
          <li class="nav-item">
            <%= link_to "Créer son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", new_user_registration_path, class: "nav-link text-primary links " %>
          </li>
          <li class="nav-item">
            <li><%= link_to "Dashboard",  new_user_registration_path, class: "nav-link text-primary links" %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Actualités",  actualites_path, class: "nav-link text-primary links" %></li>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <ul class="navbar-nav mx-auto ">
            <%= link_to "Se Connecter", new_user_session_path, class: " nav-link btn btn-sm rounded-pill nav-item ",  id:"login-btn" %>
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link btn btn-sm  btn-warning rounded-pill  nav-item ml-1", id: "signup-btn" %>
          </ul>
        </nav>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_navbar_fixed.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <%= link_to "Mon Auto-Entreprise", "/",  class: "nav-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <%= link_to "Créer son activité", company_registration_path(tab: "personal_info"),  class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", services_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", services_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "Mes services", invoices_calculate_path, class: "nav-link dropdown-toggle text-primary", id: "navbarDropdown", role: "button",  :"data-toggle"=> "dropdown", :"aria-haspopup"=> "true",  :"aria-expanded"=> "false" %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Tableau de bord", invoices_calculate_path, class: "dropdown-item text-primary links" %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link btn btn-sm btn-primary rounded-pill links " %>
        </nav>
      <% else  %>
        <ul class="navbar-nav mx-auto ">
          <li class="nav-item">
            <%= link_to "Créer son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", new_user_registration_path, class: "nav-link text-primary links " %>
          </li>
          <li class="nav-item">
            <li><%= link_to "Dashboard",  new_user_registration_path, class: "nav-link text-primary links" %></li>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <ul class="navbar-nav mx-auto ">
            <%= link_to "Se Connecter", new_user_session_path, class: " nav-link btn btn-sm btn-outline-warning rounded-pill nav-item ", id:"login" %>
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link btn btn-sm  btn-warning rounded-pill  nav-item " %>
          </ul>
        </nav>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_navbar_sansachat.html.erb
<header class="navbar-header">
  <nav class="navbar navbar-expand-lg navbar-expand-md  navbar-light bg-light fixed-top">
    <%= link_to "Mon Auto-Entreprise", "/",  class: "nav-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
          <li class="nav-item">
            <%= link_to "Créer son activité", company_registration_path(tab: "personal_info"),  class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", services_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", services_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "Dashboard", invoices_calculate_path( current_user, @invoice), class: "nav-link dropdown-toggle text-primary", id: "navbarDropdown", role: "button",  :"data-toggle"=> "dropdown", :"aria-haspopup"=> "true",  :"aria-expanded"=> "false" %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Tableau de bord", invoices_calculate_path( current_user, @invoice), class: "dropdown-item text-warning links" %>
              <a class="dropdown-item" href="#">Mes informations</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Mes écheances</a>
            </div>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link btn btn-sm btn-outline-primary rounded-pill links"%>
        </nav>
      <% else  %>
        <ul class="navbar-nav mx-auto ">
          <li class="nav-item">
            <%= link_to "Créer son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Modifier son activité", new_user_registration_path, class: "nav-link text-primary links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cesser son activité", new_user_registration_path, class: "nav-link text-primary links " %>
          </li>
          <li class="nav-item">
            <li><%= link_to "Dashboard",  new_user_registration_path, class: "nav-link text-primary links" %></li>
          </li>
          <li class="nav-item">
            <li><%= link_to "Actualités",  actualites_path, class: "nav-link text-primary links" %></li>
          </li>
        </ul>
        <nav class="navbar-light bg-light">
          <ul class="navbar-nav mx-auto ">
            <%= link_to "Se Connecter", new_user_session_path, class: " nav-link btn btn-sm btn-outline-warning rounded-pill nav-item ", id:"login-btn" %>
            <%= link_to "Créer un compte", new_user_registration_path, class: "nav-link btn btn-sm  btn-warning rounded-pill  nav-item ml-1", id: "signup-btn" %>
          </ul>
        </nav>
      <% end %>
    </div>
  </nav>
</header>