config/routes.rb
Rails.application.routes.draw do
  get '/actualites',  to: 'pages#actualites'
  devise_for :users
  devise_scope :user do
   get '/users/sign_out', to: 'devise/sessions#destroy'
end
  root to: 'pages#home'


  get'/dashboard', to: 'pages#dashboard'
  scope '/dashboard' do
    get '/cerfa_informations', to: 'pages#cerfa_informations'




    get '/invoices/:id/calculate/', to: 'invoices#calculate', as: :invoices_calculate
    post '/invoices/calculate', to: 'invoices#calculate'

    get '/my_informations', to: 'users#informations'
    get '/company_registration',  to: 'users#company_registration'
    get '/services',  to: 'pages#services'
    get '/demarches',  to: 'users#demarches'
    get '/relances/:id', to: 'relances#show', :defaults => { :format => 'docx' }
    get '/relance/new', to: 'relances#new'

    get '/miseendemeure/:id', to: 'miseendemeures#show', :defaults => { :format => 'docx' }, as: :miseendemeure_show

    get '/comptabilites/:id', to: 'comptabilites#show_calculate', :defaults => { :format => 'docx' }, as: :show_calculate

    get '/comptabilite/new', to: 'comptabilites#new', as: :new_comptabilite


    get '/comptabilites/:id/calculate/', to: 'comptabilites#calculate', as: :comptabilites_calculate
    post '/comptabilites/:id/calculate', to: 'comptabilites#calculate'

    get '/relances', to: 'relances#lettre', :defaults => { :format => 'docx' }


  get '/devis/:id/show/', to: 'devis#show', as: :devi_show

  get '/devis/search', to: 'devis#search', as: :devi_search

  get '/devis/resultat', to: 'devis#resultat', as: :resultat_devi
  get '/devis/:id/sucess/', to: 'devis#success', as: :devi_success



    # get '/personal_info', to: 'users#personal_info_users'
    # get '/company_info', to: 'users#company_info_users'
    resources :invoices
    resources :taxes, only: [:index]


    resources :comptabilites

    resources :devis
    resources :relances
    resources :miseendemeures, only: [:new, :create]
    resources :achats
    resources :clients
    resources :controledegestions

  end

  resources :users, only: [:update] # Pas propre car current_user donc pas besoin d'id mais choisi par Joseph pour faciliter les simple forms
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/devi.rb
class Devi < ApplicationRecord
  belongs_to :user
end

app/controllers/devis_controller.rb
class DevisController < ApplicationController

  def index
    @devis = Devi.where(user:current_user)
    @somme_devis = Devi.where(user:current_user).sum(:amount)
  end



  def new
   @devi = Devi.new
  end

  def create
    @devi = Devi.new(devis_params)
    @devi.user = current_user
    if @devi.save
      redirect_to new_devi_path, notice: "Votre devis a été enregistré"
    else
      render "new"
    end
  end


  def show

  end


  def success
    @devi=Devi.find(params[:id])
  end

  def search
   @resultat= find_with(params[:siren])
   redirect_to resultat_devi_path(@resultat)
  end

  def resultat
  end

  def edit
     @devi = Devi.find(params[:id])
  end

  def update
    @devi= Devi.find(params[:id])
    @devi.update!(devis_params)
    redirect_to root_path
  end

  def destroy
    @devi = Devi.find(params[:id])
    @devi.destroy
    redirect_to root
  end



  private



  KEY = ENV['DATA_KEY']


  def devis_params
    params.require(:devi).permit( :name, :object, :devis_at, :amount, :user_id)

  end

  def find_with(siren)
    if siren =""

    else
    @request = HTTParty.get("https://api.datainfogreffe.fr/api/v1/Entreprise/notapme/performance/#{siren}?millesime=2020&token=KEY")
    @result = JSON.parse(@request.body)
  end
  end


end

app/views/devis/_simple_form.html.erb
<%= simple_form_for devi do |f| %>


    <h2 class="text-warning">Créer votre devis</h2>


<div class="container">

 <form class="form-inline">
      <div class ="form-group">

       <%= f.input :name, label: "Nom du client", class:"form-control" %></div>

        <div class ="form-group">
      <%= f.input :amount, label: "Montant", class:"form-control" %></div>

      <div class ="form-group">
     <%= f.input :object, label: "Objet", class:"form-control" %></div>

      <div class ="form-group">
      &nbsp;  <%= f.input :devis_at, label: "Date du devis", as: :date, html5: true, input_html: { class:'form-control' } %></div>



</form>

  <%= f.submit "Générez votre devis", class: "btn btn-warning"%>

</div>


<% end -%>

app/views/devis/_success_form.html.erb
<%= simple_form_for devi do |f| %>


    <h2 class="text-warning">Le suuccès devis</h2>


<div class="container">

 <form class="form-inline">
      <div class ="form-group">


      <div class ="form-group">
  <%= f.checkbox :success, label: "Succès du devis",  input_html: { class:'form-control' } %></div>



</form>

  <%= f.submit "Générez votre devis", class: "btn btn-warning"%>

</div>


<% end -%>

app/views/devis/devis.docx.erb
<h2> Devis de la société <%= current_user.use_name %></h2>

<%= current_user.company_name %>
<%= current_user.company_address %>

<table>
<tbody>
  <td>
    @devi.objet
  </td>

   <td>
     @devi.amount
   </td>
</tbody>
</table>

app/views/devis/index.html.erb
<%= render 'shared/navbar_sansachat' %>


<div class="row pt-4 d-flex justify-content-between my-0 py-0">
      <div class="col-12 dashboard-chart-card">
        <div class='mb-2' style="font-size: 1.5rem">VOS devis </div>
        <div class='mt-6 py-2'>
          <div class="dashboard-upper-part-card px-0" style="width: 95%">
            <table class="table">
               <thead>
            <tr>
             <th style="border-top: 0px; font-size: 1.2rem"> Nom du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Montant</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Date du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Succès du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Retour</th>
            </tr>
            </thead>
            <tbody>
              <% @devis.each do |devi| %>
              <tr>
                <td style="border-top: 0px; font-size: 1.2rem"> <%= devi.name %></td>
                <td style="border-top: 0px; opacity: 0.6"><%= devi.amount  %> <i class="fas fa-euro-sign"></i></td>
                <td class= "date-italics" style="border-top: 0px"><%= devi.devis_at  %> </td>
                <td style="border-top: 0px"><span class="badge badge-secondary" style= "background-color: #edae2f"><%= devi.success  %> </span></td>
                <td style="border-top: 0px"><%= link_to root_path do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="À déclarer à l'URSAFF"></i><% end %></td>
              </tr>
            <% end %>
            <tr>
                <td style="border-top: 0px; font-size: 1.2rem"> Somme des devis</td>
                <td style="border-top: 0px; font-size: 1.2rem"> <%= @somme_devis %> €</td>
                <td style="border-top: 0px; font-size: 1.2rem"> Somme prévisionnelle dans le mois suivant </td>
                <td style="border-top: 0px; font-size: 1.2rem"> <%= @somme_devis %> €</td>
              </tr>
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/devis/new.html.erb
<%= render 'shared/navbar_sansachat' %>

<div class="dashboard-content">
  <div class="container">
    <div class="dashboard-information">
      <%= render "simple_form", devi: @devi  %>
      <br>


      <p> L'ajout de devis permettra de calculer votre chiffre d'affaires.</p>

      <hr>
      <%= link_to "Back to index", root_path, class:"btn btn-warning"  %>
      <%= link_to "Voir mes devis", devis_path(@user), class:"btn btn-warning" %>
       <%= link_to "Chercher le sérieux de mon cocontractant", devi_search_path, class:"btn btn-warning" %>
       <%= link_to "Entrez des chiffres du controle de gestion", new_controledegestion_path, class:"btn btn-warning"  %>
    </div>
  </div>
</div>

app/views/devis/resultat.html.erb
<%= render 'shared/navbar_sansachat' %>
<%= render '/pages/sidebar' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <h2>Recherche de solvabilité de la société</h2>
        <%= form_with( method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :siren, 'Chercher un Siren'%>
            <%= text_field_tag :siren, nil, placeholder: '123896542', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success warning' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @resultat.nil? %>

<%else%>
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6">
      <h4>info sur la Société</h4>
      <dl>
        <dt>société</dt>
        <dd><%= @resultat['Millesime"=>"2020']['A2_NiveauRentabilite'] %></dd>
        <dt>Capital</dt>
        <dd><%= @resultat['capital'] %></dd>
        <dt>Currency</dt>
        <dd><%= @resultat['currencies'].join(', ') %></dd>
        <dt>Timezone(s)</dt>
        <dd><%= @resultat['timezones'].join(', ') %></dd>
      </dl>
    </div>
  </div>
<% end %>
</div>

app/views/devis/search.html.erb
<%= render 'shared/navbar_sansachat' %>
<%= render '/pages/sidebar' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="mx-auto mt-5" style="width: 400px">
        <h2>Recherche de solvabilité de la société</h2>
        <%= form_with( method: 'get', local: true) do %>
          <div class="form-group">
            <%= label_tag :siren, 'Chercher un Siren'%>
            <%= text_field_tag :siren, nil, placeholder: '123896542', class: 'form-control' %>
          </div>
          <%= button_tag 'Search', class: 'btn btn-success warning' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/devis/show.docx.erb
<h2> Devis de la société <%= current_user.use_name %></h2>

<%= current_user.company_name %>
<%= current_user.company_address %>

<table>
<tbody>
  <td>
    @devi.objet
  </td>

   <td>
     @devi.amount
   </td>
</tbody>
</table>

app/views/devis/show.html.erb
<%= render 'shared/navbar' %>


<div class="row pt-4 d-flex justify-content-between my-0 py-0">
      <div class="col-12 dashboard-chart-card">

        <div class='mb-2' style="font-size: 1.5rem">VOS devis </div>
        <div class='mt-6 py-2'>
          <div class="dashboard-upper-part-card px-0" style="width: 95%">

            <table class="table">
            <thead>
            <tr>
             <th style="border-top: 0px; font-size: 1.2rem"> Nom du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Montant</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Date du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Succès du devis</th>
             <th style="border-top: 0px; font-size: 1.2rem"> Retour</th>
            </tr>
            </thead>
            <tbody>
              <% @devis.each do |devi| %>
              <tr>
                <td style="border-top: 0px; font-size: 1.2rem"> <%= devi.name %></td>
                <td style="border-top: 0px; opacity: 0.6"><%= devi.amount  %> <i class="fas fa-euro-sign"></i></td>
                <td class= "date-italics" style="border-top: 0px"><%= devi.invoiced_at  %> </td>
                <td style="border-top: 0px"><span class="badge badge-secondary" style= "background-color: #edae2f"><%= devi.success  %> </span></td>
                <td style="border-top: 0px"><%= link_to root_path do %><i class="fas fa-info-circle" data-toggle="tooltip" data-placement="top" title="À déclarer à l'URSAFF"></i><% end %></td>
              </tr>
            <% end %>
            <tr>
                <td style="border-top: 0px; font-size: 1.2rem"> Somme des factures</td>
                <td style="border-top: 0px; font-size: 1.2rem"> </td>

              </tr>
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/devis/success.html.erb
<%= render 'shared/navbar' %>

<div class="dashboard-content">
  <div class="container">
    <div class="dashboard-information">
      <%= render "success_form", devi: @devi  %>
      <br>


      <p> L'ajout de devis permettra de calculer votre chiffre d'affaires.</p>

      <hr>
      <%= link_to "Back to index", root_path, class:"btn btn-warning"  %>
      <%= link_to "Voir mes devis", devis_path(@user), class:"btn btn-warning" %>
       <%= link_to "Chercher le sérieux de mon cocontractant", devi_search_path, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/devis/update.html.erb
<%= render 'shared/navbar' %>
<%= render '/pages/sidebar' %>
<div class="dashboard-content">
  <div class="container">
    <div class="dashboard-information">
      <%= render "simple_form", devi: @devi  %>
      <hr>
      <p> L'ajout de devis permettra de votre k-return.</p>
      <hr>
      <%= link_to "Back to index", root_path %>
    </div>
  </div>
</div>